name: overlay_perf
description: "Telemetrie temps reel du PC (FPS, temperatures, charges, ventilateurs) en direct sur Android."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  web_socket_channel: ^3.0.3
  shared_preferences: ^2.5.5
  wakelock_plus: ^1.8.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
